//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkMediaManager.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkMediaManager.Localization.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adicionar.
        /// </summary>
        public static string adicionar {
            get {
                return ResourceManager.GetString("adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string Alerta {
            get {
                return ResourceManager.GetString("Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string Anime {
            get {
                return ResourceManager.GetString("Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animes.
        /// </summary>
        public static string Animes {
            get {
                return ResourceManager.GetString("Animes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animes, filmes e séries.
        /// </summary>
        public static string Animes_filmes_e_series {
            get {
                return ResourceManager.GetString("Animes_filmes_e_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episódio.
        /// </summary>
        public static string Episodio {
            get {
                return ResourceManager.GetString("Episodio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        public static string Feeds {
            get {
                return ResourceManager.GetString("Feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds de pesquisa.
        /// </summary>
        public static string FeedsDePesquisa {
            get {
                return ResourceManager.GetString("FeedsDePesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filme.
        /// </summary>
        public static string Filme {
            get {
                return ResourceManager.GetString("Filme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmes.
        /// </summary>
        public static string Filmes {
            get {
                return ResourceManager.GetString("Filmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato para animes:.
        /// </summary>
        public static string Formato_para_animes {
            get {
                return ResourceManager.GetString("Formato_para_animes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato para filmes:.
        /// </summary>
        public static string Formato_para_filmes {
            get {
                return ResourceManager.GetString("Formato_para_filmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato para séries:.
        /// </summary>
        public static string Formato_para_series {
            get {
                return ResourceManager.GetString("Formato_para_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geral.
        /// </summary>
        public static string Geral {
            get {
                return ResourceManager.GetString("Geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma da aplicação:.
        /// </summary>
        public static string Idioma_da_aplicacao {
            get {
                return ResourceManager.GetString("Idioma_da_aplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de pesquisa:.
        /// </summary>
        public static string Idioma_de_pesquisa {
            get {
                return ResourceManager.GetString("Idioma_de_pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar banco de dados.
        /// </summary>
        public static string Limpar_banco_de_dados {
            get {
                return ResourceManager.GetString("Limpar_banco_de_dados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de processamento:.
        /// </summary>
        public static string Metodo_de_processamento {
            get {
                return ResourceManager.GetString("Metodo_de_processamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Nao {
            get {
                return ResourceManager.GetString("Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferencias.
        /// </summary>
        public static string preferencias {
            get {
                return ResourceManager.GetString("preferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFERENCIAS.
        /// </summary>
        public static string PREFERENCIAS_ {
            get {
                return ResourceManager.GetString("PREFERENCIAS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procurar conteudo.
        /// </summary>
        public static string procurar_conteudo {
            get {
                return ResourceManager.GetString("procurar_conteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renomear.
        /// </summary>
        public static string Renomear {
            get {
                return ResourceManager.GetString("Renomear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string Selecione {
            get {
                return ResourceManager.GetString("Selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Série.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séries.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo em minutos para atualização automática dos conteúdos:.
        /// </summary>
        public static string Tempo_em_minutos_para_atualizacao_automatica_dos_conteudos {
            get {
                return ResourceManager.GetString("Tempo_em_minutos_para_atualizacao_automatica_dos_conteudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualização:.
        /// </summary>
        public static string Visualizacao {
            get {
                return ResourceManager.GetString("Visualizacao", resourceCulture);
            }
        }
    }
}
