//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkMediaManager.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkMediaManager.Localization.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a pasta onde estão armazenadas as séries....
        /// </summary>
        public static string Selecione_a_pasta_onde_estao_armazenadas_as_series {
            get {
                return ResourceManager.GetString("Selecione_a_pasta_onde_estao_armazenadas_as_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a pasta onde estão armazenados os animes....
        /// </summary>
        public static string Selecione_a_pasta_onde_estao_armazenados_os_animes {
            get {
                return ResourceManager.GetString("Selecione_a_pasta_onde_estao_armazenados_os_animes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a pasta onde estão armazenados os filmes....
        /// </summary>
        public static string Selecione_a_pasta_onde_estao_armazenados_os_filmes {
            get {
                return ResourceManager.GetString("Selecione_a_pasta_onde_estao_armazenados_os_filmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a pasta onde serão armazenados os arquivos &apos;.torrent&apos;....
        /// </summary>
        public static string Selecione_a_pasta_onde_serao_armazenados_os_arquivos_Torrent {
            get {
                return ResourceManager.GetString("Selecione_a_pasta_onde_serao_armazenados_os_arquivos_Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor fora dos limites permitidos..
        /// </summary>
        public static string Valor_fora_dos_limites_permitidos {
            get {
                return ResourceManager.GetString("Valor_fora_dos_limites_permitidos", resourceCulture);
            }
        }
    }
}
